### Importando dataframe

In [13]:
import pandas as pd
import numpy as np


df = pd.read_csv("Musical_instruments_reviews.csv")

display(df)

reviewerID        asin  \
0      A2IBPI20UZIR0U  1384719342   
1      A14VAT5EAX3D9S  1384719342   
2      A195EZSQDW3E21  1384719342   
3      A2C00NNG1ZQQG2  1384719342   
4       A94QU4C90B1AX  1384719342   
...               ...         ...   
10256  A14B2YH83ZXMPP  B00JBIVXGC   
10257   A1RPTVW5VEOSI  B00JBIVXGC   
10258   AWCJ12KBO5VII  B00JBIVXGC   
10259  A2Z7S8B5U4PAKJ  B00JBIVXGC   
10260  A2WA8TDCTGUADI  B00JBIVXGC   

                                           reviewerName   helpful  \
0      cassandra tu "Yeah, well, that's just like, u...    [0, 0]   
1                                                  Jake  [13, 14]   
2                         Rick Bennette "Rick Bennette"    [1, 1]   
3                             RustyBill "Sunday Rocker"    [0, 0]   
4                                         SEAN MASLANKA    [0, 0]   
...                                                 ...       ...   
10256                                   Lonnie M. Adams    [0, 0]   
10257                                Michael J. Edelman    [0, 0]   
10258                                  Michael L. Knapp    [0, 0]   
10259                           Rick Langdon "Scriptor"    [0, 0]   
10260                                   TheTerrorBeyond    [0, 0]   

                                              reviewText  overall  \
0      Not much to write about here, but it does exac...      5.0   
1      The product does exactly as it should and is q...      5.0   
2      The primary job of this device is to block the...      5.0   
3      Nice windscreen protects my MXL mic and preven...      5.0   
4      This pop filter is great. It looks and perform...      5.0   
...                                                  ...      ...   
10256            Great, just as expected.  Thank to all.      5.0   
10257  I've been thinking about trying the Nanoweb st...      5.0   
10258  I have tried coated strings in the past ( incl...      4.0   
10259  Well, MADE by Elixir and DEVELOPED with Taylor...      4.0   
10260  These strings are really quite good, but I wou...      4.0   

                                                 summary  unixReviewTime  \
0                                                   good      1393545600   
1                                                   Jake      1363392000   
2                                   It Does The Job Well      1377648000   
3                          GOOD WINDSCREEN FOR THE MONEY      1392336000   
4                  No more pops when I record my vocals.      1392940800   
...                                                  ...             ...   
10256                                         Five Stars      1405814400   
10257  Long life, and for some players, a good econom...      1404259200   
10258                                   Good for coated.      1405987200   
10259                                        Taylor Made      1404172800   
10260  These strings are really quite good, but I wou...      1405468800   

        reviewTime  
0      02 28, 2014  
1      03 16, 2013  
2      08 28, 2013  
3      02 14, 2014  
4      02 21, 2014  
...            ...  
10256  07 20, 2014  
10257   07 2, 2014  
10258  07 22, 2014  
10259   07 1, 2014  
10260  07 16, 2014  

[10261 rows x 9 columns]

### Identificando necessidade de tratamento

In [14]:
'''
Considerando o foco no uso dos dados da coluna reviewText, linhas em que essa coluna não esteja preenchida serão deletadas
'''

print(df.info())

df = df.dropna(subset=["reviewText"])

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10261 entries, 0 to 10260
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   reviewerID      10261 non-null  object 
 1   asin            10261 non-null  object 
 2   reviewerName    10234 non-null  object 
 3   helpful         10261 non-null  object 
 4   reviewText      10254 non-null  object 
 5   overall         10261 non-null  float64
 6   summary         10261 non-null  object 
 7   unixReviewTime  10261 non-null  int64  
 8   reviewTime      10261 non-null  object 
dtypes: float64(1), int64(1), object(7)
memory usage: 721.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 10254 entries, 0 to 10260
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   reviewerID      10254 non-null  object 
 1   asin            10254 non-null  object 
 2   reviewerName    10227 non-null  object 


### Função de Pré-Processamento

In [16]:
import re
import spacy
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# inicialização do spacy
nlp = spacy.load('en_core_web_sm')

# inicialização do NLTK
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    # lowercasing
    text = text.lower()
    
    # remoção de caracteres não alfanuméricos
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    
    # tokenização com NLTK
    tokens = word_tokenize(text)
    
    # remoção de stopwords com NLTK
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    
    # lematização com spacy
    lemmatized_tokens = [lemmatizer.lemmatize(token.lemma_, 'v') for token in nlp(" ".join(tokens))]
    
    # reunir os tokens lematizados em uma string
    preprocessed_text = " ".join(lemmatized_tokens)
    
    return preprocessed_text


# tratamento da coluna reviewText
df['nltk_token'] = df['reviewText'].apply(preprocess_text)
display(df)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


reviewerID        asin  \
0      A2IBPI20UZIR0U  1384719342   
1      A14VAT5EAX3D9S  1384719342   
2      A195EZSQDW3E21  1384719342   
3      A2C00NNG1ZQQG2  1384719342   
4       A94QU4C90B1AX  1384719342   
...               ...         ...   
10256  A14B2YH83ZXMPP  B00JBIVXGC   
10257   A1RPTVW5VEOSI  B00JBIVXGC   
10258   AWCJ12KBO5VII  B00JBIVXGC   
10259  A2Z7S8B5U4PAKJ  B00JBIVXGC   
10260  A2WA8TDCTGUADI  B00JBIVXGC   

                                           reviewerName   helpful  \
0      cassandra tu "Yeah, well, that's just like, u...    [0, 0]   
1                                                  Jake  [13, 14]   
2                         Rick Bennette "Rick Bennette"    [1, 1]   
3                             RustyBill "Sunday Rocker"    [0, 0]   
4                                         SEAN MASLANKA    [0, 0]   
...                                                 ...       ...   
10256                                   Lonnie M. Adams    [0, 0]   
10257                                Michael J. Edelman    [0, 0]   
10258                                  Michael L. Knapp    [0, 0]   
10259                           Rick Langdon "Scriptor"    [0, 0]   
10260                                   TheTerrorBeyond    [0, 0]   

                                              reviewText  overall  \
0      Not much to write about here, but it does exac...      5.0   
1      The product does exactly as it should and is q...      5.0   
2      The primary job of this device is to block the...      5.0   
3      Nice windscreen protects my MXL mic and preven...      5.0   
4      This pop filter is great. It looks and perform...      5.0   
...                                                  ...      ...   
10256            Great, just as expected.  Thank to all.      5.0   
10257  I've been thinking about trying the Nanoweb st...      5.0   
10258  I have tried coated strings in the past ( incl...      4.0   
10259  Well, MADE by Elixir and DEVELOPED with Taylor...      4.0   
10260  These strings are really quite good, but I wou...      4.0   

                                                 summary  unixReviewTime  \
0                                                   good      1393545600   
1                                                   Jake      1363392000   
2                                   It Does The Job Well      1377648000   
3                          GOOD WINDSCREEN FOR THE MONEY      1392336000   
4                  No more pops when I record my vocals.      1392940800   
...                                                  ...             ...   
10256                                         Five Stars      1405814400   
10257  Long life, and for some players, a good econom...      1404259200   
10258                                   Good for coated.      1405987200   
10259                                        Taylor Made      1404172800   
10260  These strings are really quite good, but I wou...      1405468800   

        reviewTime                                         nltk_token  
0      02 28, 2014  much write exactly suppose filter pop sound re...  
1      03 16, 2013  product exactly quite affordablei realize doub...  
2      08 28, 2013  primary job device block breath would otherwis...  
3      02 14, 2014  nice windscreen protect mxl mic prevent pop th...  
4      02 21, 2014  pop filter great look perform like studio filt...  
...            ...                                                ...  
10256  07 20, 2014                                 great expect thank  
10257   07 2, 2014  I ve think try nanoweb string bite put high pr...  
10258  07 22, 2014  try coat string past include elixir never fond...  
10259   07 1, 2014  well make elixir develop taylor guitar string ...  
10260  07 16, 2014  string really quite good would not call perfec...  

[10254 rows x 10 columns]

### Vetorização por BOW e TFIFD

In [33]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer


# exemplo de corpus de textos
corpus = df["nltk_token"].tolist()

# inicializar o CountVectorizer para a abordagem Bag of Words (BoW)
count_vectorizer = CountVectorizer()
bow_matrix = count_vectorizer.fit_transform(corpus)

# inicializar o TfidfVectorizer para a abordagem TF-IDF
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

# obtendo os tokens e matriz BoW
bow_tokens = count_vectorizer.get_feature_names_out()
print("Tokens BoW:", bow_tokens)
print("Matriz BoW:\n", bow_matrix.toarray())

# obtendo os tokens e matriz TF-IDF
tfidf_tokens = tfidf_vectorizer.get_feature_names_out()
print("Tokens TF-IDF:", tfidf_tokens)
print("Matriz TF-IDF:\n", tfidf_matrix.toarray())

Tokens BoW: ['000' '00045' '001' ... 'zvex' 'zylgian' 'zz']
Matriz BoW:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Tokens TF-IDF: ['000' '00045' '001' ... 'zvex' 'zylgian' 'zz']
Matriz TF-IDF:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### Modelos de classificação clássicos

In [24]:
'''
Percebe-se que o número de amostras encontra-se desbalanceado. Será aplicado o método SMOTE para lidar com esse problema
'''
print(df[["overall"]].groupby("overall").value_counts())


overall
1.0     217
2.0     250
3.0     772
4.0    2083
5.0    6932
Name: count, dtype: int64


In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report


X, y = df["nltk_token"].values, df["overall"].values

# Vetorização usando TF-IDF
tfidf_vectorizer = TfidfVectorizer(max_features=len(tfidf_tokens))
X_tfidf = tfidf_vectorizer.fit_transform(X)

# aplicar método SMOTE para balanceamento das amostras
smote = SMOTE(sampling_strategy="minority", k_neighbors=15)
X_sm, y_sm = smote.fit_resample(X_tfidf, y)

# dividir os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X_sm, y_sm, test_size=0.2, random_state=42)

# treinar um classificador Naive Bayes
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)
y_pred_nb = nb_classifier.predict(X_test)

# treinar um classificador SVM
svm_classifier = SVC(kernel='linear')
svm_classifier.fit(X_train, y_train)
y_pred_svm = svm_classifier.predict(X_test)

# treinar um classificador KNN
knn_classifier = KNeighborsClassifier(n_neighbors=101, p=2, metric='euclidean')
knn_classifier.fit(X_train, y_train)
y_pred_knn = knn_classifier.predict(X_test)

# avaliar os classificadores
accuracy_nb = accuracy_score(y_test, y_pred_nb)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
accuracy_knn = accuracy_score(y_test, y_pred_knn)

# acurácia
print("Acurácia do Naive Bayes:", accuracy_nb)
print("Acurácia do SVM:", accuracy_svm)
print("Acurácia do KNN:", accuracy_knn)


# relatório de classificação
target_names = ['1 estrela', '2 estrelas', '3 estrelas', '4 estrelas', '5 estrelas']

print("\nRelatório de Classificação do Naive Bayes:")
print(classification_report(y_test, y_pred_nb, target_names=target_names, zero_division=1))

print("\nRelatório de Classificação do SVM:")
print(classification_report(y_test, y_pred_svm, target_names=target_names, zero_division=1))

print("\nRelatório de Classificação do KNN:")
print(classification_report(y_test, y_pred_knn, target_names=target_names, zero_division=1))

Acurácia do Naive Bayes: 0.7810842663523866
Acurácia do SVM: 0.8078962875662935
Acurácia do KNN: 0.4004124926340601

Relatório de Classificação do Naive Bayes:
              precision    recall  f1-score   support

   1 estrela       0.87      1.00      0.93      1359
  2 estrelas       1.00      0.00      0.00        50
  3 estrelas       1.00      0.00      0.00       157
  4 estrelas       1.00      0.00      0.00       444
  5 estrelas       0.71      0.93      0.80      1384

    accuracy                           0.78      3394
   macro avg       0.92      0.39      0.35      3394
weighted avg       0.83      0.78      0.70      3394


Relatório de Classificação do SVM:
              precision    recall  f1-score   support

   1 estrela       0.98      1.00      0.99      1359
  2 estrelas       1.00      0.00      0.00        50
  3 estrelas       0.42      0.03      0.06       157
  4 estrelas       0.35      0.05      0.09       444
  5 estrelas       0.70      0.98      0.82 

### Tokenização com TensorFlow

In [36]:
'''
Atribuição de ID's às palavras
'''
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer


# exemplo de lista de textos
texts = df["nltk_token"].tolist()

# criar um objeto Tokenizer
tokenizer = Tokenizer()

# ajustar o Tokenizer aos textos
tokenizer.fit_on_texts(texts)

print(tokenizer.word_index)

{'use': 1, 'not': 2, 'guitar': 3, 'sound': 4, 'well': 5, 'one': 6, 'get': 7, 'string': 8, 'good': 9, 'like': 10, 'great': 11, 'i': 12, 'do': 13, 'pedal': 14, 'work': 15, 'make': 16, 'buy': 17, 'play': 18, 'would': 19, 'pick': 20, 'amp': 21, 'price': 22, 'really': 23, 'need': 24, 'go': 25, 'little': 26, 'look': 27, 've': 28, 'much': 29, 'time': 30, 'easy': 31, 'quality': 32, 'tone': 33, 'nice': 34, 'also': 35, 'cable': 36, 'stand': 37, 'tuner': 38, 'want': 39, 'm': 40, 'strap': 41, 'try': 42, 'set': 43, 'mic': 44, 'come': 45, 'tune': 46, 'say': 47, 'thing': 48, 'find': 49, 'think': 50, 'product': 51, 'even': 52, 'year': 53, 'give': 54, 'feel': 55, 'long': 56, 'recommend': 57, 'take': 58, 'could': 59, 'you': 60, 'way': 61, 'small': 62, 'seem': 63, 'love': 64, 'acoustic': 65, 'put': 66, 'hold': 67, 'still': 68, 'case': 69, 'cheap': 70, 're': 71, 'bite': 72, 'keep': 73, 'fit': 74, 's': 75, 'back': 76, 'lot': 77, 'record': 78, 'right': 79, 'two': 80, 'instrument': 81, 'see': 82, 'first': 83

### RNN com TensorFlow

In [51]:
from tensorflow.keras.preprocessing.sequence import pad_sequences


# mapear as classificações para rótulos numéricos (-1 por conta das restrições da sparse_categorical_crossentropy)
df['label'] = df['overall'].astype(int) - 1

# dividir df em X e y
X = df["nltk_token"]
y = df["label"]

# dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# tokenização e padding
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

train_sequences = tokenizer.texts_to_sequences(X_train)
test_sequences = tokenizer.texts_to_sequences(X_test)

max_sequence_length = max([len(seq) for seq in train_sequences])
train_sequences_padded = pad_sequences(train_sequences, maxlen=max_sequence_length, padding='post')
test_sequences_padded = pad_sequences(test_sequences, maxlen=max_sequence_length, padding='post')

# aplicar SMOTE para balanceamento
smote = SMOTE()
train_sequences_padded, y_train = smote.fit_resample(train_sequences_padded, y_train)

# definir modelo
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=128, input_length=max_sequence_length),
    tf.keras.layers.SimpleRNN(64),
    tf.keras.layers.Dense(5, activation='softmax')
])

# compilar o modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# treinar o modelo
model.fit(train_sequences_padded, y_train, epochs=10, batch_size=32, validation_data=(test_sequences_padded, y_test))

Epoch 1/10
859/859 [==============================] - 320s 371ms/step - loss: 1.6160 - accuracy: 0.2007 - val_loss: 1.6322 - val_accuracy: 0.0268
Epoch 2/10
859/859 [==============================] - 322s 375ms/step - loss: 1.6141 - accuracy: 0.1992 - val_loss: 1.7295 - val_accuracy: 0.1824
Epoch 3/10
859/859 [==============================] - 324s 377ms/step - loss: 1.6135 - accuracy: 0.2026 - val_loss: 1.6818 - val_accuracy: 0.0254
Epoch 4/10
859/859 [==============================] - 322s 375ms/step - loss: 1.6150 - accuracy: 0.1999 - val_loss: 1.5381 - val_accuracy: 0.7006
Epoch 5/10
859/859 [==============================] - 327s 381ms/step - loss: 1.6138 - accuracy: 0.2029 - val_loss: 1.5972 - val_accuracy: 0.7006
Epoch 6/10
859/859 [==============================] - 389s 453ms/step - loss: 1.6217 - accuracy: 0.2006 - val_loss: 1.5573 - val_accuracy: 0.3608
Epoch 7/10
859/859 [==============================] - 467s 544ms/step - loss: 1.6137 - accuracy: 0.2079 - val_loss: 1.6178 -

### LSTM Unidirecional

In [52]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM


# mapear as classificações para rótulos numéricos (-1 por conta das restrições da sparse_categorical_crossentropy)
df['label'] = df['overall'].astype(int) - 1

# dividir df em X e y
X = df["nltk_token"]
y = df["label"]

# dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# tokenização e padding
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

train_sequences = tokenizer.texts_to_sequences(X_train)
test_sequences = tokenizer.texts_to_sequences(X_test)

max_sequence_length = max([len(seq) for seq in train_sequences])
train_sequences_padded = pad_sequences(train_sequences, maxlen=max_sequence_length, padding='post')
test_sequences_padded = pad_sequences(test_sequences, maxlen=max_sequence_length, padding='post')

# aplicar SMOTE para balanceamento
smote = SMOTE()
train_sequences_padded, y_train = smote.fit_resample(train_sequences_padded, y_train)

# definir modelo com LSTM unidirecional
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=128, input_length=max_sequence_length),
    LSTM(64),
    tf.keras.layers.Dense(5, activation='softmax')
])

# compilar o modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# treinar o modelo
model.fit(train_sequences_padded, y_train, epochs=10, batch_size=32, validation_data=(test_sequences_padded, y_test))

Epoch 1/10
859/859 [==============================] - 726s 842ms/step - loss: 1.6101 - accuracy: 0.2005 - val_loss: 1.6149 - val_accuracy: 0.1824
Epoch 2/10
859/859 [==============================] - 773s 900ms/step - loss: 1.6097 - accuracy: 0.1989 - val_loss: 1.5998 - val_accuracy: 0.7006
Epoch 3/10
859/859 [==============================] - 754s 878ms/step - loss: 1.6097 - accuracy: 0.2007 - val_loss: 1.6025 - val_accuracy: 0.7006
Epoch 4/10
859/859 [==============================] - 703s 818ms/step - loss: 1.6097 - accuracy: 0.1953 - val_loss: 1.6052 - val_accuracy: 0.7006
Epoch 5/10
859/859 [==============================] - 703s 818ms/step - loss: 1.6097 - accuracy: 0.1950 - val_loss: 1.6109 - val_accuracy: 0.0254
Epoch 6/10
859/859 [==============================] - 696s 810ms/step - loss: 1.6097 - accuracy: 0.2004 - val_loss: 1.5996 - val_accuracy: 0.0648
Epoch 7/10
859/859 [==============================] - 699s 814ms/step - loss: 1.6096 - accuracy: 0.2001 - val_loss: 1.6214 -

### LSTM Bidirecional

In [53]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Bidirectional, LSTM


# mapear as classificações para rótulos numéricos (-1 por conta das restrições da sparse_categorical_crossentropy)
df['label'] = df['overall'].astype(int) - 1

# dividir df em X e y
X = df["nltk_token"]
y = df["label"]

# dividir os dados em treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# tokenização e padding
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

train_sequences = tokenizer.texts_to_sequences(X_train)
test_sequences = tokenizer.texts_to_sequences(X_test)

max_sequence_length = max([len(seq) for seq in train_sequences])
train_sequences_padded = pad_sequences(train_sequences, maxlen=max_sequence_length, padding='post')
test_sequences_padded = pad_sequences(test_sequences, maxlen=max_sequence_length, padding='post')

# aplicar SMOTE para balanceamento
smote = SMOTE()
train_sequences_padded, y_train = smote.fit_resample(train_sequences_padded, y_train)

# definir modelo com LSTM unidirecional
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=128, input_length=max_sequence_length),
    Bidirectional(LSTM(64)),
    tf.keras.layers.Dense(5, activation='softmax')
])

# compilar o modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# treinar o modelo
model.fit(train_sequences_padded, y_train, epochs=10, batch_size=32, validation_data=(test_sequences_padded, y_test))

Epoch 1/10
859/859 [==============================] - 1576s 2s/step - loss: 1.4560 - accuracy: 0.3397 - val_loss: 1.2020 - val_accuracy: 0.5826
Epoch 2/10
859/859 [==============================] - 1574s 2s/step - loss: 1.2788 - accuracy: 0.4512 - val_loss: 1.2336 - val_accuracy: 0.5544
Epoch 3/10
859/859 [==============================] - 1665s 2s/step - loss: 1.0649 - accuracy: 0.5576 - val_loss: 1.3860 - val_accuracy: 0.5319
Epoch 4/10
859/859 [==============================] - 1693s 2s/step - loss: 0.8309 - accuracy: 0.6712 - val_loss: 1.4167 - val_accuracy: 0.5695
Epoch 5/10
859/859 [==============================] - 1710s 2s/step - loss: 0.6318 - accuracy: 0.7541 - val_loss: 1.7219 - val_accuracy: 0.5280
Epoch 6/10
859/859 [==============================] - 1712s 2s/step - loss: 0.4713 - accuracy: 0.8235 - val_loss: 1.8952 - val_accuracy: 0.4949
Epoch 7/10
859/859 [==============================] - 1538s 2s/step - loss: 0.3471 - accuracy: 0.8724 - val_loss: 1.9444 - val_accuracy:

In [ ]:
"""
Os modelos possivelmente apresentaram uma acurácia pequena considerando que as distinções entre as classificações do meio 
(2, 3 e 4) podem ser mais difíceis de serem percebidas. Uma alternativa seria agrupar essas classificações entre 
detratora (1 e 2) e propagadora (3, 4 e 5), transformando o problema de classificação multiclasse em um problema binário 
"""